apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-hello-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: k8s-web-hello-deployment
  template:
    metadata:
      labels:
        app: k8s-web-hello-deployment
    spec:
      containers:
      - name: k8s-web-hello-deployment
        image: angelnuernberg/k8s-web-hello
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
    